remote_theme: olivier3lanc/Jekyll-LibDoc
title: VvE Snijderskazerne
description: Website van Vereniging van Eigenaren Generaal Snijderskazerne
url: https://snijderskazerne.nl
# baseurl: /Jekyll-LibDoc/_site # the subpath of your site, e.g. /blog
#permalink: /:path/:basename/:output_ext
#destination: ../your/new/path # Build relative path destination. The destination directory e.g. /blog
#keep_files: [cache]
markdown: kramdown
